name: flutter_image_compress_macos
description: The implementation of macOS for flutter_image_compress.
version: 1.0.3
homepage: https://github.com/fluttercandies/flutter_image_compress
publish_to: https://brewery.mindy.kr

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface:
    hosted: https://brewery.mindy.kr
    version: ^1.0.5
  
flutter:
  plugin:
    implements: flutter_image_compress
    platforms:
      macos:
        pluginClass: FlutterImageCompressMacosPlugin
        dartPluginClass: FlutterImageCompressMacos