name: flutter_image_compress_common
description: Compress image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 1.0.6
publish_to: https://brewery.mindy.kr

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface:
    hosted: https://brewery.mindy.kr
    version: ^1.0.5

flutter:
  plugin:
    implements: flutter_image_compress
    platforms:
      android:
        package: com.fluttercandies.flutter_image_compress
        pluginClass: ImageCompressPlugin
        dartPluginClass: FlutterImageCompressCommon
      ios:
        pluginClass: ImageCompressPlugin
        dartPluginClass: FlutterImageCompressCommon
