name: flutter_image_compress
description: Compress Pictures. Can effectively reduce the size of the transmission.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 3.0.0
publish_to: https://brewery.mindy.kr
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface: 
    hosted: https://brewery.mindy.kr
    version: ^1.0.5
  flutter_image_compress_common:
    hosted: https://brewery.mindy.kr
    version: ^1.0.6
  flutter_image_compress_web:
    hosted: https://brewery.mindy.kr
    version: ^0.1.5
  flutter_image_compress_macos:
    hosted: https://brewery.mindy.kr
    version: ^1.0.3
  flutter_image_compress_ohos:
    hosted: https://brewery.mindy.kr
    version: ^0.0.3

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_image_compress_common
      ios:
        default_package: flutter_image_compress_common
      macos:
        default_package: flutter_image_compress_macos
      web:
        default_package: flutter_image_compress_web
      ohos:
        default_package: flutter_image_compress_ohos
